#pragma once

#define FASTFETCH_PROJECT_NAME "fastfetch"
#define FASTFETCH_PROJECT_VERSION ""
#define FASTFETCH_PROJECT_VERSION_MAJOR 
#define FASTFETCH_PROJECT_VERSION_MINOR 
#define FASTFETCH_PROJECT_VERSION_PATCH 
#define FASTFETCH_PROJECT_VERSION_GIT ""
#define FASTFETCH_PROJECT_VERSION_TWEAK ""
#define FASTFETCH_PROJECT_VERSION_TWEAK_NUM 
#define FASTFETCH_PROJECT_CMAKE_BUILD_TYPE "Release"
#define FASTFETCH_PROJECT_HOMEPAGE_URL ""
#define FASTFETCH_PROJECT_DESCRIPTION ""
#define FASTFETCH_PROJECT_LICENSE ""

#define FASTFETCH_TARGET_DIR_ROOT ""
#define FASTFETCH_TARGET_DIR_USR ""
#define FASTFETCH_TARGET_DIR_HOME ""
#define FASTFETCH_TARGET_DIR_ETC ""

#define FASTFETCH_TARGET_DIR_INSTALL_SYSCONF ""
